
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.l2ashdz.appgraficar.analizadores.sintactico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LINEA = 10;
  public static final int MULTIPLICACION = 22;
  public static final int DIVISION = 23;
  public static final int SUMA = 20;
  public static final int CURVA = 6;
  public static final int ANIMAR = 3;
  public static final int CAFE = 19;
  public static final int PAREN_APERTURA = 24;
  public static final int CUADRADO = 8;
  public static final int OBJETO = 4;
  public static final int VERDE = 15;
  public static final int ROJO = 14;
  public static final int PAREN_CIERRE = 25;
  public static final int GRAFICAR = 2;
  public static final int AMARILLO = 16;
  public static final int COMA = 26;
  public static final int EOF = 0;
  public static final int MORADO = 18;
  public static final int NUMERO = 27;
  public static final int error = 1;
  public static final int POLIGONO = 11;
  public static final int CIRCULO = 7;
  public static final int AZUL = 13;
  public static final int ANTERIOR = 5;
  public static final int NEGRO = 12;
  public static final int NARANJA = 17;
  public static final int RECTANGULO = 9;
  public static final int RESTA = 21;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "GRAFICAR",
  "ANIMAR",
  "OBJETO",
  "ANTERIOR",
  "CURVA",
  "CIRCULO",
  "CUADRADO",
  "RECTANGULO",
  "LINEA",
  "POLIGONO",
  "NEGRO",
  "AZUL",
  "ROJO",
  "VERDE",
  "AMARILLO",
  "NARANJA",
  "MORADO",
  "CAFE",
  "SUMA",
  "RESTA",
  "MULTIPLICACION",
  "DIVISION",
  "PAREN_APERTURA",
  "PAREN_CIERRE",
  "COMA",
  "NUMERO"
  };
}

